name: Deploy to Production

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: self-hosted
    env:
      ENVIRONMENT: production
      DOMAIN: ${{ secrets.DOMAIN }}
      STACK_NAME: ${{ secrets.STACK_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      FIRST_SUPERUSER: ${{ secrets.FIRST_SUPERUSER }}
      FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      EMAILS_FROM_EMAIL: ${{ secrets.EMAILS_FROM_EMAIL }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      ECOMMERCE_API_KEY: ${{ secrets.ECOMMERCE_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print environment variables
        run: |
          echo "ECOMMERCE_API_KEY: $ECOMMERCE_API_KEY"
          echo "ENVIRONMENT: $ENVIRONMENT"
          echo "DOMAIN: $DOMAIN"
          echo "STACK_NAME: $STACK_NAME"
          echo "SECRET_KEY: $SECRET_KEY"
          echo "FIRST_SUPERUSER: $FIRST_SUPERUSER"
          echo "FIRST_SUPERUSER_PASSWORD: $FIRST_SUPERUSER_PASSWORD"
          echo "SMTP_HOST: $SMTP_HOST"
          echo "SMTP_USER: $SMTP_USER"
          echo "SMTP_PASSWORD: $SMTP_PASSWORD"
          echo "EMAILS_FROM_EMAIL: $EMAILS_FROM_EMAIL"
          echo "POSTGRES_PASSWORD: $POSTGRES_PASSWORD"
          echo "SENTRY_DSN: $SENTRY_DSN"

      - run: docker-compose --file docker-compose.yml --project-name ${{ secrets.STACK_NAME }} build
      - run: docker-compose --file docker-compose.yml --project-name ${{ secrets.STACK_NAME }} up -d
