name: Deploy to Production

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write environment variables to .env file
        run: |
          echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}" >> .env
          echo "DOMAIN=${{ secrets.DOMAIN }}" >> .env
          echo "STACK_NAME=${{ secrets.STACK_NAME }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "FIRST_SUPERUSER=${{ secrets.FIRST_SUPERUSER }}" >> .env
          echo "FIRST_SUPERUSER_PASSWORD=${{ secrets.FIRST_SUPERUSER_PASSWORD }}" >> .env
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env
          echo "SMTP_USER=${{ secrets.SMTP_USER }}" >> .env
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env
          echo "EMAILS_FROM_EMAIL=${{ secrets.EMAILS_FROM_EMAIL }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env
          echo "ECOMMERCE_API_KEY=${{ secrets.API_KEY }}" >> .env

      - name: Print environment variables
        run: cat .env

      - name: Build Docker containers
        run: docker compose --file docker-compose.yml --project-name ${{ secrets.STACK_NAME }} build

      - name: Start Docker containers
        run: docker compose up -d
